apiVersion: v2
name: support-service
description: AuraBank Customer Support Service Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: aurabank-library
    version: 0.1.0
    repository: "file://../_library"
